version: '3.9'


networks:
  brewhelper-network:

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BrewHelperDev1!"
    networks:
      - brewhelper-network
    volumes:
      -  brewHelperDb:/var/opt/mssql

  brewhelper:
    image: ${DOCKER_REGISTRY-}brewhelper
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5002
      - ConnectionStrings__SQL=Server=db;Database=BrewHelper;User=sa;Password=BrewHelperDev1!;
      - ConnectionStrings__Authentication=Server=db;Database=BrewHelperUsers;User=sa;Password=BrewHelperDev1!;
    build:
      context: ./BrewHelper/BrewHelper/
    depends_on:
      - db
    networks:
      - brewhelper-network
    entrypoint: bash wait_for_it.sh db:1433 -t 0 -- dotnet BrewHelper.dll
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  dashboard:
    image: ${DOCKER_REGISTRY-}brewhelper-dashboard
    build:
      context: ./brewhelper-dashboard/
    depends_on:
      - brewhelper
    ports:
      - "5000:80"
    networks:
      - brewhelper-network

volumes:
  brewHelperDb: