version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        expose:  
            - 1433
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "BrewHelperDev1!"
            ACCEPT_EULA: "Y"