version: '3.9'


networks:
  brewhelper-network:

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BrewHelperDev1!"
    networks:
      - brewhelper-network
    volumes:
      -  brewHelperDb:/var/opt/mssql

  brewhelper:
    image: ${DOCKER_REGISTRY-}brewhelper
    build:
      context: .
      dockerfile: BrewHelper/Dockerfile
    depends_on:
      - db
    networks:
      - brewhelper-network
    entrypoint: bash wait_for_it.sh db:1433 -t 0 -- dotnet BrewHelper.dll

volumes:
  brewHelperDb: